# Generated by Django 4.0.5 on 2022-06-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
