# Generated by Django 4.0.5 on 2022-06-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Updated_date',
            field=models.DateField(null=True),
        ),
    ]
