# Generated by Django 4.0.5 on 2022-06-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Updated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
