# Generated by Django 4.0.5 on 2022-06-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
